// noinspection JSUnusedGlobalSymbols

export {default as ArrowShortRight} from "src/assets/img/icons/landing/arrow-short-right.svg"
export {default as ArrowWideLeft} from "src/assets/img/icons/landing/arrow-wide-left.svg"
export {default as ArrowWideRight} from "src/assets/img/icons/landing/arrow-wide-right.svg"
export {default as BackText} from "src/assets/img/icons/landing/back-text.svg"
export {default as ChevronCircleDown} from "src/assets/img/icons/landing/chevron-circle-down.svg"
export {default as ChevronCircleRight} from "src/assets/img/icons/landing/chevron-circle-right.svg"
export {default as Circuit} from "src/assets/img/icons/landing/circuit.svg"
export {default as LogoBright} from "src/assets/img/icons/landing/logo-bright.svg"
export {default as LogoDark} from "src/assets/img/icons/landing/logo-dark.svg"
export {default as LogoGrey} from "src/assets/img/icons/landing/logo-grey.svg"
export {default as Objective} from "src/assets/img/icons/landing/objective.svg"
export {default as PromoIcLd1} from "src/assets/img/landing/promo-ic-ld-1.svg"
export {default as PromoIcLd2} from "src/assets/img/landing/promo-ic-ld-2.svg"
export {default as PromoIcLd3} from "src/assets/img/landing/promo-ic-ld-3.svg"
export {default as PromoIcLd4} from "src/assets/img/landing/promo-ic-ld-4.svg"
export {default as ReactLogo} from "src/assets/img/icons/landing/react_logo.svg"
export {default as Smartphone} from "src/assets/img/icons/landing/smartphone.svg"
